spring:
  application:
    name: vending-machine
  security:
    user:
      name: admin
      password: password

server:
  port: 8081

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      path: /h2-console